package com.entity;
// Generated 2017-6-14 14:48:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * AnotherYear generated by hbm2java
 */
@Entity
@Table(name = "AnotherYear")
public class AnotherYear implements java.io.Serializable {

	private int id;
	private Date springDate;
	private Date summerDate;
	private Date autumnDate;
	private Date winterDate;
	private Integer winterDay;

	public AnotherYear() {
	}

	public AnotherYear(int id) {
		this.id = id;
	}

	public AnotherYear(int id, Date springDate, Date summerDate, Date autumnDate, Date winterDate) {
		this.id = id;
		this.springDate = springDate;
		this.summerDate = summerDate;
		this.autumnDate = autumnDate;
		this.winterDate = winterDate;
	}

	@GenericGenerator(name = "generator", strategy = "identity")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Spring_Date", length = 23)
	public Date getSpringDate() {
		return this.springDate;
	}

	public void setSpringDate(Date springDate) {
		this.springDate = springDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Summer_Date", length = 23)
	public Date getSummerDate() {
		return this.summerDate;
	}

	public void setSummerDate(Date summerDate) {
		this.summerDate = summerDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Autumn_Date", length = 23)
	public Date getAutumnDate() {
		return this.autumnDate;
	}

	public void setAutumnDate(Date autumnDate) {
		this.autumnDate = autumnDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Winter_Date", length = 23)
	public Date getWinterDate() {
		return this.winterDate;
	}

	public void setWinterDate(Date winterDate) {
		this.winterDate = winterDate;
	}

	@Column(name = "Winter_Day")
	public Integer getWinterDay() {
		return winterDay;
	}

	public void setWinterDay(Integer winterDay) {
		this.winterDay = winterDay;
	}


}
