package com.entity;
// Generated 2017-6-23 9:36:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Holiday generated by hbm2java
 */
@Entity
@Table(name = "Holiday", schema = "dbo", catalog = "Weather")
public class Holiday implements java.io.Serializable {

	private int id;
	private String title;
	private String contents;

	public Holiday() {
	}

	public Holiday(int id) {
		this.id = id;
	}

	public Holiday(int id, String title, String contents) {
		this.id = id;
		this.title = title;
		this.contents = contents;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Contents")
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

}
