package com.entity;
// Generated 2017-6-23 14:46:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ImpWeather generated by hbm2java
 */
@Entity
@Table(name = "ImageData")
public class ImageData implements java.io.Serializable {

	private Integer id;
	private String name;
	private String icon;

	
	public ImageData() {
	}

	public ImageData(int id) {
		this.id = id;
	}

	public ImageData(int id, String name, String icon) {
		this.id = id;
		this.name = name;
		this.icon = icon;
	}

	@GenericGenerator(name = "generator", strategy = "identity")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "icon")
	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}
}
