package com.entity;
// Generated 2017-6-19 14:59:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Precipitation generated by hbm2java
 */
@Entity
@Table(name = "Precipitation")
public class Precipitation implements java.io.Serializable {

	private Integer id;
	private String stationName;
	private Integer stationIdD;
	private Integer dateYear;
	private Integer dateMon;
	private Integer dateDay;
	private Date dateDate;
	private Double temAvg;
	private Double temMax;
	private Double temMin;
	private Double preTime2008;
	private Double preTime0820;
	private Double preTime2020;
	private Double preTime0808;
	private Date dateYearMonDay;

	public Precipitation() {
	}

	public Precipitation(Integer id) {
		this.id = id;
	}

	public Precipitation(Integer id, String stationName, Integer stationIdD, Integer dateYear, Integer dateMon,
			Integer dateDay, Date dateDate, Double temAvg, Double temMax, Double temMin, Double preTime2008,
			Double preTime0820, Double preTime2020, Double preTime0808) {
		this.id = id;
		this.stationName = stationName;
		this.stationIdD = stationIdD;
		this.dateYear = dateYear;
		this.dateMon = dateMon;
		this.dateDay = dateDay;
		this.dateDate = dateDate;
		this.temAvg = temAvg;
		this.temMax = temMax;
		this.temMin = temMin;
		this.preTime2008 = preTime2008;
		this.preTime0820 = preTime0820;
		this.preTime2020 = preTime2020;
		this.preTime0808 = preTime0808;
	}

	@GenericGenerator(name = "generator", strategy = "identity")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Station_Name")
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@Column(name = "Station_Id_d")
	public Integer getStationIdD() {
		return this.stationIdD;
	}

	public void setStationIdD(Integer stationIdD) {
		this.stationIdD = stationIdD;
	}

	@Column(name = "DateYear")
	public Integer getDateYear() {
		return this.dateYear;
	}

	public void setDateYear(Integer dateYear) {
		this.dateYear = dateYear;
	}

	@Column(name = "DateMon")
	public Integer getDateMon() {
		return this.dateMon;
	}

	public void setDateMon(Integer dateMon) {
		this.dateMon = dateMon;
	}

	@Column(name = "DateDay")
	public Integer getDateDay() {
		return this.dateDay;
	}

	public void setDateDay(Integer dateDay) {
		this.dateDay = dateDay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateDate", length = 23)
	public Date getDateDate() {
		return this.dateDate;
	}

	public void setDateDate(Date dateDate) {
		this.dateDate = dateDate;
	}

	@Column(name = "TEM_Avg", precision = 15, scale = 0)
	public Double getTemAvg() {
		return this.temAvg;
	}

	public void setTemAvg(Double temAvg) {
		this.temAvg = temAvg;
	}

	@Column(name = "TEM_Max", precision = 15, scale = 0)
	public Double getTemMax() {
		return this.temMax;
	}

	public void setTemMax(Double temMax) {
		this.temMax = temMax;
	}

	@Column(name = "TEM_Min", precision = 15, scale = 0)
	public Double getTemMin() {
		return this.temMin;
	}

	public void setTemMin(Double temMin) {
		this.temMin = temMin;
	}

	@Column(name = "PRE_Time_2008", precision = 15, scale = 0)
	public Double getPreTime2008() {
		return this.preTime2008;
	}

	public void setPreTime2008(Double preTime2008) {
		this.preTime2008 = preTime2008;
	}

	@Column(name = "PRE_Time_0820", precision = 15, scale = 0)
	public Double getPreTime0820() {
		return this.preTime0820;
	}

	public void setPreTime0820(Double preTime0820) {
		this.preTime0820 = preTime0820;
	}

	@Column(name = "PRE_Time_2020", precision = 15, scale = 0)
	public Double getPreTime2020() {
		return this.preTime2020;
	}

	public void setPreTime2020(Double preTime2020) {
		this.preTime2020 = preTime2020;
	}

	@Column(name = "PRE_Time_0808", precision = 15, scale = 0)
	public Double getPreTime0808() {
		return this.preTime0808;
	}

	public void setPreTime0808(Double preTime0808) {
		this.preTime0808 = preTime0808;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateYearMonDay", length = 23)
	public Date getDateYearMonDay() {
		return dateYearMonDay;
	}

	public void setDateYearMonDay(Date dateYearMonDay) {
		this.dateYearMonDay = dateYearMonDay;
	}

}
