package com.entity;
// Generated 2017-6-12 17:01:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DataQuery2 generated by hbm2java
 */
@Entity
@Table(name = "SiteMonthAvg")
public class SiteMonthAvg implements java.io.Serializable {

	private Integer id;
	private String site;
	private String month;
	private Double atEarly;
	private Double atMid;
	private Double atLate;
	private Double atMonth;
	private Double rfEarly;
	private Double rfMid;
	private Double rfLate;
	private Double rfMonth;

	public SiteMonthAvg() {
	}

	public SiteMonthAvg(Integer id) {
		this.id = id;
	}

	public SiteMonthAvg(Integer id, String site, String month, Double atEarly, Double atMid, Double atLate, Double atMonth,
			Double rfEarly, Double rfMid, Double rfLate, Double rfMonth) {
		this.id = id;
		this.site = site;
		this.month = month;
		this.atEarly = atEarly;
		this.atMid = atMid;
		this.atLate = atLate;
		this.atMonth = atMonth;
		this.rfEarly = rfEarly;
		this.rfMid = rfMid;
		this.rfLate = rfLate;
		this.rfMonth = rfMonth;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Site", length = 50)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "Month", length = 50)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "AT_Early", precision = 15, scale = 0)
	public Double getAtEarly() {
		return this.atEarly;
	}

	public void setAtEarly(Double atEarly) {
		this.atEarly = atEarly;
	}

	@Column(name = "AT_Mid", precision = 15, scale = 0)
	public Double getAtMid() {
		return this.atMid;
	}

	public void setAtMid(Double atMid) {
		this.atMid = atMid;
	}

	@Column(name = "AT_Late", precision = 15, scale = 0)
	public Double getAtLate() {
		return this.atLate;
	}

	public void setAtLate(Double atLate) {
		this.atLate = atLate;
	}

	@Column(name = "AT_Month", precision = 15, scale = 0)
	public Double getAtMonth() {
		return this.atMonth;
	}

	public void setAtMonth(Double atMonth) {
		this.atMonth = atMonth;
	}

	@Column(name = "RF_Early", precision = 15, scale = 0)
	public Double getRfEarly() {
		return this.rfEarly;
	}

	public void setRfEarly(Double rfEarly) {
		this.rfEarly = rfEarly;
	}

	@Column(name = "RF_Mid", precision = 15, scale = 0)
	public Double getRfMid() {
		return this.rfMid;
	}

	public void setRfMid(Double rfMid) {
		this.rfMid = rfMid;
	}

	@Column(name = "RF_Late", precision = 15, scale = 0)
	public Double getRfLate() {
		return this.rfLate;
	}

	public void setRfLate(Double rfLate) {
		this.rfLate = rfLate;
	}

	@Column(name = "RF_Month", precision = 15, scale = 0)
	public Double getRfMonth() {
		return this.rfMonth;
	}

	public void setRfMonth(Double rfMonth) {
		this.rfMonth = rfMonth;
	}

}
