package com.entity;
// Generated 2017-7-25 10:08:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Mod generated by hbm2java
 */
@Entity
@Table(name = "Mod")
public class Mod implements java.io.Serializable {

	private int id;
	private int year;
	private Date modDay;
	private Date meiDay;
	private Integer meiyuLength;
	private Double meiyuAmount;

	public Mod() {
	}

	public Mod(int id, int year) {
		this.id = id;
		this.year = year;
	}

	public Mod(int id, int year, Date modDay, Date meiDay, Integer meiyuLength, Double meiyuAmount) {
		this.id = id;
		this.year = year;
		this.modDay = modDay;
		this.meiDay = meiDay;
		this.meiyuLength = meiyuLength;
		this.meiyuAmount = meiyuAmount;
	}

	@GenericGenerator(name = "generator", strategy = "identity")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModDay", length = 23)
	public Date getModDay() {
		return this.modDay;
	}

	public void setModDay(Date modDay) {
		this.modDay = modDay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MeiDay", length = 23)
	public Date getMeiDay() {
		return this.meiDay;
	}

	public void setMeiDay(Date meiDay) {
		this.meiDay = meiDay;
	}

	@Column(name = "MeiyuLength")
	public Integer getMeiyuLength() {
		return this.meiyuLength;
	}

	public void setMeiyuLength(Integer meiyuLength) {
		this.meiyuLength = meiyuLength;
	}

	@Column(name = "MeiyuAmount", precision = 15, scale = 0)
	public Double getMeiyuAmount() {
		return this.meiyuAmount;
	}

	public void setMeiyuAmount(Double meiyuAmount) {
		this.meiyuAmount = meiyuAmount;
	}

}
